### ISSUE TITLE
접속 불가 현상

### ISSUE THREAD

**Issue by joonas-yoon** [alps-jbnu/alps-acm#8]
3000 포트로도 접속이 안되는 데, 중단한건가요?
내후년을 위해 틈틈히 개발해서 완성해볼까 싶습니다.

**Comment by sjw0687** [comment]
내일 다시 열도록 하겠음!

**Comment by sjw0687** [comment]
늦었네, 복구 완료

**Comment by joonas-yoon** [comment]
서버 켜질때마다 같이 켜지게 스크립트 작성하는 건 어떨까요?

**Comment by sjw0687** [comment]
이미 그러고 있어 meteor-up으로 디플로이하고 있거든

**Comment by sjw0687** [comment]
한번 예기치 않게 꺼졌나보네 mongodb lock 파일이랑 지우고 다시 고쳐서 원상복귀시킴
